grafana:
  enabled: true
  adminPassword: "glo7008" 

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: localhost 
        paths:
          - path: /grafana(/|$)(.*)
            pathType: Prefix
    tls: [] 

  persistence:
    enabled: true
    storageClassName: "" 
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.logging.svc.cluster.local:3100
          isDefault: true

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  plugins:
    - grafana-piechart-panel #
